---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels: 
    app: fs
spec:
  containers:
  - name: fs
    image: kodekloud/fileserver
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /web
        name: data-store
        subPath: dbdata      
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
  labels:
    app: fs
spec:
  selector:
    app: fs
  type: NodePort
  ports:
    - name: fs
      protocol: TCP
      targetPort: 8080
      nodePort: 31200